### ISSUE TITLE
Support of Rollotron 1213 DECT Shutters

### ISSUE THREAD

**Issue by sapgitest** [SeydX/homebridge-fritz-platform#173] opened 2021-04-03 21:16 UTC
The support of the new device rollotron dect for the fritz box would be great.

**Comment by sisihuet** [comment] 2021-04-30 13:06
+1: I have the device and can contribute

**Comment by Mark323513** [comment] 2021-05-03 11:09
I have two devices and can contribute

**Comment by JohannesPl** [comment] 2021-06-03 12:02
Hi. Is there a current state for this topic?

**Comment by SeydX** [comment] 2021-06-06 05:15
Hey,

im planning to add support for shades/blinds in v5.2

**Comment by Donni1966** [comment] 2021-06-08 08:24
Hi i can support also ... have a device installed

**Comment by ulrgaer** [comment] 2021-06-13 09:36
> Hey,
> 
> im planning to add support for shades/blinds in v5.2

Hi, I will still be able to support by testing, I have the device installed.

**Comment by SeydX** [comment] 2021-06-14 14:43
Hey guys, working currently on the next big major release, can anyone capture the traffic from the fritz smarthome app on opening/closing/stopping the blinds and also setting it to specific position

**Comment by ulrgaer** [comment] 2021-06-14 16:58
Hi,

If you let me know more detail what should be measured. 

Best
Uli

**Comment by Donni1966** [comment] 2021-06-14 20:08
Hi SeydX, 

i have implementiert the blend with node-red and the node-red-contrib-fritzapi palette and there is support for a blind. I have http requester installed on my iphone and the Smarthome App from fritz. So if you give me some details i can make a log am Wednesday (homeoffice :-)) and log some details.

**Comment by SeydX** [comment] 2021-06-14 20:26
@Donni1966 

it would be nice to know if it is possible to adjust the target position with eg `setlevelpercentage&level=50` or if it only works with following cmd: `setblind&target=open` / `setblind&target=close` / `setblind&target=stop`

**Comment by Donni1966** [comment] 2021-06-14 20:31
Hi, 

the API in node-red support setlevelpercent and this works fine. The homekit is invert the value. so 100 is closed and zero is open. Means, i invert the value and generate a homekit object "Windowcovering" 

the fritz api s also understand the level adjustment ...

**Comment by SeydX** [comment] 2021-06-14 23:28
Thx @Donni1966 

So if i set 100% in HomeKit (for full open)  i need to send `setlevelpercentage&level=0` correct?

**Comment by Donni1966** [comment] 2021-06-15 04:34
Yes. Exact. 
Currentposition 100 -> setlevel 0

**Comment by SeydX** [comment] 2021-06-15 08:53
v6 Beta is online 

`sudo npm i -g homebridge-fritz-platform@beta`

example blind config:

```json
…
"smarthome": [
  {
      "active": true,
      "name": "Rollotron",
      "ain": "01234567890",
      "accType": "blind"
  }
]
…
```

I would be happy if you could test the beta and give feedback if blinds work without problems for you.

It would also be helpful to enable debug in config during the beta phase (`"debug": true`)

# NOTE

The changes are NOT committed to the beta branch yet. Version 6 is fully backward compatible but there are some little changes in the config.json

To make sure that everything works correctly you have to enter `"active": true` in the config for all devices, presence, wol, smarthome, network, callmonitor, extras

Another change concerns the presence option in the config: `onDelay` and `offDelay` must now be entered directly in the presence under the user, so it is now possible to set separate values for all users

# Important

Version 6 now needs Node >= v14 and homebridge >= v1.3.0

**Comment by sisihuet** [comment] 2021-06-15 09:54
> v6 Beta is online
control of the blind does work for me - but Home App always shows "closed" independent of actual position

**Comment by SeydX** [comment] 2021-06-15 09:55
> v6 Beta is online
> control of the blind does work for me - but Home App always shows "closed" independent of actual position

Can u post your log pls (debug enabled)

**Comment by sisihuet** [comment] 2021-06-15 09:59
> > v6 Beta is online
> > control of the blind does work for me - but Home App always shows "closed" independent of actual position
> 
> Can u post your log pls (debug enabled)

Rollo: Position 88
[15/06/2021, 11:56:05] [FritzPlatform] [DEBUG] Rollo: Send CMD: {"switchcmd":"setlevelpercentage","level":12}

Rollo: {"name":"Rollo Schlaf","id":"2000","ain":"xxxxx2961-1","online":1,"bitmask":"335888","busy":0,"battery":false,"alert":{"state":0},"temperature":false,"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":{"position":{"level":31,"levelpercentage":12}},"thermostat":false,"light":false}

but Home App still shows "closed"

**Comment by SeydX** [comment] 2021-06-15 10:07
@sisihuet 

can u take a screen recording so i can see exactly how the device behaves in HomeKit when opened/closed

**Comment by sisihuet** [comment] 2021-06-15 10:17
sure - video shows me just setting to 83% and then not touching the iPhone any more
https://www.dropbox.com/s/3b06adcw03beuwl/Mein%20Film%208.MOV?dl=0

**Comment by SeydX** [comment] 2021-06-15 10:40
@sisihuet 

can u try the latest beta pls?

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by sisihuet** [comment] 2021-06-15 11:22
behavior is different now - but not in a good way
With open blind - pressing the icon in Home appe toggles between "closed" and "is opening" (with spinning circle) - but no action from the blind.
Direct control to positions works, but setting to e.g. 95% leads to white icon in Home "is opening" (with spinning circle)

PS: hope it is ok for you to have this as an debugging session with me reporting issues - I love the plugin and I want to be sure you know I want to help not complain

**Comment by SeydX** [comment] 2021-06-15 13:13
> behavior is different now - but not in a good way
> With open blind - pressing the icon in Home appe toggles between "closed" and "is opening" (with spinning circle) - but no action from the blind.
> Direct control to positions works, but setting to e.g. 95% leads to white icon in Home "is opening" (with spinning circle)
> 
> PS: hope it is ok for you to have this as an debugging session with me reporting issues - I love the plugin and I want to be sure you know I want to help not complain

New Beta online, can u try it pls?

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by sisihuet** [comment] 2021-06-15 13:20
Now I get the following error message:
[15/06/2021, 15:18:48] [FritzPlatform] Rollo (smarthome-blind): Can not find position data - "accType" and/or options correct?
Behavior is back to beta.6 (jumps to "closed" after a few seconds)

**Comment by SeydX** [comment] 2021-06-15 13:24
> Now I get the following error message:
> [15/06/2021, 15:18:48] [FritzPlatform] Rollo (smarthome-blind): Can not find position data - "accType" and/or options correct?
> Behavior is back to beta.6 (jumps to "closed" after a few seconds)

Nice, that helps me a lot, for some reason, the plugin does not contain any data for the position, i will write a little script for you to obtain the data

**Comment by SeydX** [comment] 2021-06-15 13:38
> Now I get the following error message:
> [15/06/2021, 15:18:48] [FritzPlatform] Rollo (smarthome-blind): Can not find position data - "accType" and/or options correct?
> Behavior is back to beta.6 (jumps to "closed" after a few seconds)

New Beta online, can u try it pls?

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by sisihuet** [comment] 2021-06-15 13:49
beta.9 same as beta.8 
[15/06/2021, 15:49:25] [FritzPlatform] Rollo (smarthome-blind): Can not find position data - "accType" and/or options correct?

**Comment by SeydX** [comment] 2021-06-15 14:16
> beta.9 same as beta.8
> [15/06/2021, 15:49:25] [FritzPlatform] Rollo (smarthome-blind): Can not find position data - "accType" and/or options correct?

I created a little script which collects all information about the smarthome devices (which i need to fix this). Could you try it pls and copy/paste the output here? You can also send it via email (seydx@outlook.de)


## Instruction:

1. Use following command to automatically download the file into the "homebridge-fritz-platform" directory (maybe you need to adjust the path to the directory, otherwise the command will download the file to: `/usr/local/lib/node_modules/homebridge-fritz-platform`)

```
wget https://gist.githubusercontent.com/SeydX/69fc4b818cd2dacd189da73a9dbf34f0/raw/7354febe480af5d66b997a07d67bd75e0205aef3/smarthome.js /usr/local/lib/node_modules/homebridge-fritz-platform
```

2. Open the file with an editor or nano and adjust the lines 1-4 (host, username, password)

```
sudo nano /usr/local/lib/node_modules/homebridge-fritz-platform/smarthome.js
```

3. Save the file and execute it with following command:

```
node /usr/local/lib/node_modules/homebridge-fritz-platform/smarthome.js
```

4. And copy/paste or send the output via email

**Comment by Donni1966** [comment] 2021-06-15 14:40
done it. 

nice by side effect - the config has change and my fritz!box was not supplied to Homekit. And later i read there is a new switch true false not for all subs :-) 

so if the box is not supply to hk nothing is supply. 
Andy way i change the config. 

Thanx for support Seydx

**Comment by SeydX** [comment] 2021-06-15 14:49
@sisihuet 

New Beta is online, can u try it pls?

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by sisihuet** [comment] 2021-06-15 14:53
beta.10 tested:
control no longer works
position not available

[15/06/2021, 16:52:17] [FritzPlatform] Rollo (smarthome-blind): Position 64
[15/06/2021, 16:52:30] [FritzPlatform] Rollo (smarthome-blind): Can not find position data - "accType" and/or options correct?

blinds are completly open

**Comment by SeydX** [comment] 2021-06-15 15:03
@sisihuet

New Beta is online, can u try it pls?

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by sisihuet** [comment] 2021-06-15 15:13
beta.11
Control with the slider is back - works again.
But, now i have either "is opening" or "is closing"  (with spinning circle) as the state. Clicking the icon does not trigger any action.

**Comment by SeydX** [comment] 2021-06-15 15:16
> beta.11
> Control with the slider is back - works again.
> But, now i have either "is opening" or "is closing" (with spinning circle) as the state. Clicking the icon does not trigger any action.

Thats the normal behavior, thats how blinds work. But after next „polling“ the state (opening/closing) should be stopped?

**Comment by SeydX** [comment] 2021-06-15 15:21
So the intended behavior is like following: (assume you hab set polling timer to : 20 in config)

- You set blind position to 50%
- The accessory show opening/closing depending on the target state (with a circle) and the blind should move
- After the next polling (20s) the current state (opening/closing with circle) should stop and the accessory should show the current state

**Comment by SeydX** [comment] 2021-06-15 15:39
> "options": {
> "polling": {
> "timer": 10
> 
> blinds are fully up or fully down or at 50% --> icon with spinning circle
> pushing the icon changes "is opening" <-> "is closing" - but no effect on blinds
> read back of manally entered position to slider does not work
> --> only setting a position with the slider brings blinds to correct position

So reading the current state and displaying it in Apple Home works?

Setting the position via slider also works without problems? 

Only toggling the icon doesnt work?

**Comment by SeydX** [comment] 2021-06-15 15:40
@Donni1966 

also tested v6 blinds?

**Comment by Donni1966** [comment] 2021-06-15 19:04
> also tested v6 blinds?

i am not sure what you mean. 

i try beta 11 - install reboot. But nothing happen. Now i can set the Level, get the log entry ... but the blind do not move in any direction. 

my run Node-red solution works fine.

**Comment by SeydX** [comment] 2021-06-15 19:12
@Donni1966 

can u post your config pls? And also maybe the log (debug enabled)

The plugin refresh the states on polling, so if you have set a new value with the fritz app, the state should be refreshed in homekit after next polling

**Comment by Donni1966** [comment] 2021-06-15 19:23
no problem: 
`{
    "name": "FritzPlatform",
    "debug": true,
    "devices": [
        {
            "active": true,
            "name": "WG",
            "host": "192.168.2.1",
            "username": "***",
            "password": "***
[log20211506_donni.txt](https://github.com/SeydX/homebridge-fritz-platform/files/6658176/log20211506_donni.txt)
",
            "ssl": true,
            "tr064": true,
            "igd": false,
            "manufacturer": "AVM",
            "model": "Fritz!Box 7140",
            "serialNumber": "07.12",
            "master": true,
            "connection": "dsl"
        }
    ],
    "presence": [
        {
            "active": true,
            "name": "LCD Galerie",
            "address": "C0:D9:62:EB:70:2C",
            "accType": "motion",
            "ping": false
        },
        {
            "active": true,
            "name": "LCD Schlafzimmer",
            "address": "78:AB:BB:EE:B2:1E",
            "accType": "motion",
            "ping": false
        },
        {
            "active": true,
            "name": "LCD Gast",
            "address": "A8:A6:48:65:C6:31",
            "accType": "motion",
            "ping": false
        }
    ],
    "smarthome": [
        {
            "active": true,
            "name": "SW Kugel",
            "ain": "087610141686",
            "energy": true,
            "temperature": true,
            "accType": "switch"
        },
        {
            "active": true,
            "name": "SW Mustang",
            "ain": "087610270360",
            "energy": true,
            "temperature": true,
            "accType": "switch"
        },
        {
            "active": true,
            "name": "SW Terrasse",
            "ain": "087610259188",
            "energy": true,
            "temperature": true,
            "accType": "switch"
        },
        {
            "active": true,
            "name": "SW Werkbank",
            "ain": "087610297364",
            "energy": true,
            "temperature": true,
            "accType": "switch"
        },
        {
            "active": true,
            "name": "SW Werkstattlichter",
            "ain": "087610141691",
            "energy": true,
            "temperature": true,
            "accType": "switch"
        },
        {
            "active": true,
            "name": "Rollotron",
            "ain": "142760444622",
            "accType": "blind"
        }
    ],
    "callmonitor": {
        "active": false,
        "port": 1012
    },
    "extras": {
        "alarm": {
            "active": false
        },
        "wakeup": {
            "active": false
        },
        "ringlock": {
            "active": false
        },
        "phoneBook": {
            "active": false
        }
    },
    "options": {
        "presence": {
            "accType": "occupancy"
        },
        "polling": {
            "timer": 10
        }
    },
    "telegram": {
        "active": false
    },
    "platform": "FritzPlatform"
}`

**Comment by ulrgaer** [comment] 2021-06-15 19:23
sorry for late response. I installed beta 11. I can see the level an levelpercentage changing when controlling via Fritz SmartHome app. When I change controls or level in HomeKit nothing is happening.

**Comment by Donni1966** [comment] 2021-06-15 19:28
> sorry for late response. I installed beta 11. I can see the level an levelpercentage changing when controlling via Fritz SmartHome app. When I change controls or level in HomeKit nothing is happening.

i do not get the level when i control is anywhere

**Comment by SeydX** [comment] 2021-06-15 19:39
> > sorry for late response. I installed beta 11. I can see the level an levelpercentage changing when controlling via Fritz SmartHome app. When I change controls or level in HomeKit nothing is happening.
> 
> i do not get the level when i control is anywhere

The API for your Rollotron has following output:

``
[DEBUG] Rollotron (smarthome-blind): {"name":"Fensterrollo","id":"2000","ain":"142760444622","online":1,"bitmask":"335888","busy":0,"battery":false,"alert":{"state":0},"temperature":false,"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":{"position":{"level":0,"levelpercentage":0}},"thermostat":false,"light":false}
``

With following blind data: 

``
"blind":{"position":{"level":0,"levelpercentage":0}}
``

this means that your rollotron is fully open (100% in HomeKit) - i cant see any changes from your smarthome app

But i can also see that the SET cmd does not work for you

the payload for the SET command is following:

``
[DEBUG] Rollotron (smarthome-blind): Send CMD: {"switchcmd":"setlevelpercentage","level":100}
``

Hmmm, weird…

**Comment by ulrgaer** [comment] 2021-06-15 19:45
To be more precise, I see the level change in homebridge debug mode (homebridge protocol window) NOT in HomeKit app.

**Comment by SeydX** [comment] 2021-06-15 19:46
> To be more precise, I see the level change in homebridge debug mode (homebridge protocol window) NOT in HomeKit app.

Can u post a screenshot from the state in HomeKit and the Log where i can see the differents between them pls

**Comment by ulrgaer** [comment] 2021-06-15 19:55
sure:

HomeBridge Debug protokoll


[15.6.2021, 21:48:37] [FritzPlatform] [DEBUG] Polling SMARTHOME accessories
[15.6.2021, 21:48:38] [FritzPlatform] [DEBUG] Rollo Fenster Aquarium  (smarthome-blind): {"name":"Rollo Aquarium","id":"2000","ain":"142760503505","online":1,"bitmask":"335888","busy":0,"battery":false,"alert":{"state":0},"temperature":false,"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":{"position":{"level":54,"levelpercentage":21}},"thermostat":false,"light":false}
[15.6.2021, 21:49:40] [FritzPlatform] [DEBUG] Polling SMARTHOME accessories
[15.6.2021, 21:49:40] [FritzPlatform] [DEBUG] Rollo Fenster Aquarium  (smarthome-blind): {"name":"Rollo Aquarium","id":"2000","ain":"142760503505","online":1,"bitmask":"335888","busy":0,"battery":false,"alert":{"state":0},"temperature":false,"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":{"position":{"level":0,"levelpercentage":0}},"thermostat":false,"light":false}

all the time the same screen in HomeKit, without any change
![Rollo Fenster Aquarium](https://user-images.githubusercontent.com/83507349/122115069-4f544780-ce24-11eb-8b07-010987381aed.PNG)

**Comment by SeydX** [comment] 2021-06-15 21:02
@ulrgaer @Donni1966 @sisihuet 

New Beta is online, could u all try it pls?

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by Donni1966** [comment] 2021-06-15 21:12
installed ... but no status change 

`[15/06/2021, 23:09:52] [FritzPlatform] [DEBUG] Rollotron (smarthome-blind): {"name":"Fensterrollo","id":"2000","ain":"142760444622-1","online":1,"bitmask":"335888","busy":0,"battery":false,"alert":{"state":0},"temperature":false,"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":{"position":{"level":156,"levelpercentage":61}},"thermostat":false,"light":false}`

![Bildschirmfoto 2021-06-15 um 23 11 18](https://user-images.githubusercontent.com/61660957/122124025-ffc74900-ce2e-11eb-8474-dc45ca627463.png)
right my node-red Object left the SmartHome Fritz object 

sorry but movements i can try tomorrow - my wife is in bed :-)

**Comment by SeydX** [comment] 2021-06-15 21:28
@ulrgaer @Donni1966 @sisihuet

Aaand again ^^ New Beta is online, could u all try it pls?

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by Donni1966** [comment] 2021-06-15 21:34
![Bildschirmfoto 2021-06-15 um 23 33 46](https://user-images.githubusercontent.com/61660957/122126500-22a72c80-ce32-11eb-91df-22525b597de9.png)

looks great :-)

let me try tomorrow the movements than i can give you the feedback

**Comment by ulrgaer** [comment] 2021-06-16 04:17
Installation and first testing looks fine, more detailed testing tonight.  It’s beta 13.

**Comment by SeydX** [comment] 2021-06-16 04:49
> Installation and first testing looks fine, more detailed testing tonight. It’s beta 13.

Beta 15 online

**Comment by Donni1966** [comment] 2021-06-16 05:36
Hi, 

so up down and the positions go flawlessly. I personally would miss a faster display of the levels in the movements, but that is marginal. I have set the polling for movements to 1s in my NODE-RED solution. This gives more dynamic - but as I said, only fine tuning. 

Really good work ... Beta 15 is running for me. Thank you

**Comment by SeydX** [comment] 2021-06-16 05:47
> Hi,
> 
> so up down and the positions go flawlessly. I personally would miss a faster display of the levels in the movements, but that is marginal. I have set the polling for movements to 1s in my NODE-RED solution. This gives more dynamic - but as I said, only fine tuning.
> 
> Really good work ... Beta 15 is running for me. Thank you

Sure, lower polling timer such as 1s would allow to see the real state of the device. But the plugin has too much functionality. That would dramatically increase the query made in the own network and that can be result on lower responses for other devices in the network

**Comment by SeydX** [comment] 2021-06-16 05:48
But glad to hear that everything works like a charm

**Comment by Donni1966** [comment] 2021-06-16 05:51
> Sure, lower polling timer such as 1s would allow to see the real state of the device. But the plugin has too much functionality. That would dramatically increase the query made in the own network and that can be result on lower responses for other devices in the network

absolut not real need - and in my network are enough traffic with Smarthome :-)

**Comment by ulrgaer** [comment] 2021-06-16 19:49
I installed beat 15, perfect everything working fine. As well the blends are working with rule, scene. Great job

**Comment by ulrgaer** [comment] 2021-06-16 20:36
just installed the beta as well on an other pi, its now Beta 17, is there any difference ?

**Comment by SeydX** [comment] 2021-06-16 21:07
> just installed the beta as well on an other pi, its now Beta 17, is there any difference ?

nope, nothing for the dect blinds, but many other improvements and features like childLocks, reconnect, wifiUnits, open window switch (for smarthome thermostats),  filterIncoming (for callmonitor) and some minor bugfixes

**Comment by Mark323513** [comment] 2021-06-16 22:05
Installed beta on my Synology with Docker.
Works fine

Von meinem iPad gesendet

**Comment by SeydX** [comment] 2021-06-16 22:41
Closing this issue since it was included in the beta (see last comment) and to keep track of which feature requests are still open.

**Closed by SeydX** 2021-06-16 22:41 UTC
Labels: enhancement, v6

**Comment by SeydX** [comment] 2021-06-16 22:56
https://github.com/SeydX/homebridge-fritz-platform/issues/191
