### ISSUE TITLE
Negative temperatur on Fritz DECT 210

### ISSUE THREAD

**Issue by franzose79** [SeydX/homebridge-fritz-platform#137] opened 2020-11-28 18:21 UTC
Negative temperatures will not display in HomeKit and just displays "no response".

Anything above 0 degree Celsius works fine.

**Comment by SeydX** [comment] 2020-11-29 02:21
@franzose79 

Tried with latest version v5.0.16?

**Comment by franzose79** [comment] 2020-11-29 05:53
> @franzose79
> 
> Tried with latest version v5.0.16?

Yes, latest version installed.

**Comment by SeydX** [comment] 2020-11-29 08:08
@franzose79 

Can u post your config pls

**Comment by franzose79** [comment] 2020-11-29 08:15
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CC:22",
        "manufacturer": "homebridge.io",
        "model": "homebridge",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "sudo": true,
            "log": {
                "method": "custom",
                "command": "journalctl -o cat -n 500 -f -u homebridge"
            }
        },
        {
            "platform": "FritzPlatform",
            "devices": {
                "FRITZ!Box 7590": {
                    "active": false,
                    "host": "192.168.10.1",
                    "port": 49000,
                    "username": "xyz",
                    "password": "pwd",
                    "type": "cable",
                    "master": true,
                    "mesh": false,
                    "readOnly": false,
                    "options": {
                        "reconnect": false,
                        "wifi2": [
                            false,
                            false
                        ],
                        "wifi5": [
                            false,
                            false
                        ],
                        "wifiGuest": [
                            false,
                            false
                        ],
                        "wps": [
                            false,
                            false
                        ],
                        "aw": [
                            false,
                            false
                        ],
                        "deflection": [
                            false,
                            false
                        ],
                        "led": [
                            false,
                            false
                        ],
                        "lock": [
                            false,
                            false
                        ]
                    }
                }
            },
            "smarthome": {
                "Stehlampe": {
                    "active": true,
                    "ain": "087610422222",
                    "tempSensor": true,
                    "devType": "switch"
                },
                "Schrank": {
                    "active": true,
                    "ain": "116300062222",
                    "tempSensor": true,
                    "devType": "switch"
                },
                "Weihnachten": {
                    "active": true,
                    "ain": "116570387777",
                    "tempSensor": true,
                    "devType": "switch"
                }
            },
            "callmonitor": {
                "active": false,
                "ip": "192.168.10.1",
                "port": 1012,
                "country": "DE",
                "incomingTo": [
                    ""
                ],
                "outgoingFrom": [
                    "",
                    ""
                ]
            },
            "presence": {
                "user": [
                    {
                        "active": true,
                        "name": "xxx",
                        "address": "192.168.10.33"
                    },
                    {
                        "active": true,
                        "name": "yyy",
                        "address": "192.168.10.28"
                    }
                ],
                "anyone": true,
                "offDelay": 90,
                "onDelay": 15,
                "ping": false
            },
            "wol": [
                {
                    "active": false,
                    "name": "Test Device",
                    "address": "00:00:00:00:00:00"
                }
            ],
            "phoneBook": {
                "active": true,
                "blacklists": []
            },
            "alarm": {
                "active": false,
                "telNr": "",
                "duration": 30
            },
            "wakeup": {
                "active": false,
                "internNr": "",
                "duration": 30
            },
            "ringlock": {
                "active": false,
                "DECTphones": 1,
                "start": "11:00",
                "end": "22:00"
            },
            "broadband": {
                "active": false,
                "measureTime": 5
            },
            "extReboot": {
                "active": false,
                "cmdOn": "",
                "cmdOff": ""
            },
            "telegram": {
                "active": false,
                "token": "",
                "chatID": "",
                "presence": {
                    "in": "",
                    "out": "",
                    "anyoneIn": "",
                    "anyoneOut": ""
                },
                "callmonitor": {
                    "incoming": "",
                    "disconnected": ""
                },
                "alarm": {
                    "activated": "",
                    "deactivated": ""
                },
                "extReboot": {
                    "start": "",
                    "finish": ""
                }
            },
            "polling": 10,
            "timeout": 10,
            "clearCache": false,
            "debug": false,
            "disableAutoSearch": false,
            "disableAutoConfig": false
        }
    ],
    "accessories": [],
    "id": "config"
} `

**Comment by franzose79** [comment] 2020-11-29 08:16
dECT 210 is labelles Weihnachten

**Comment by SeydX** [comment] 2020-11-29 08:19
@franzose79 

Your config is from v4. You need to update your config.

Look at the example configuration pls

https://github.com/SeydX/homebridge-fritz-platform/blob/master/example/example-config.json

**Comment by franzose79** [comment] 2020-11-29 08:22
Was the issue fixed in v5?

I had the Same issue before upgrading to 5.0.16 ...

**Comment by SeydX** [comment] 2020-11-29 08:26
The issue is fixed in v5.0.16. But to use v5, you need to upgrade your config.json

**Closed** 2020-11-30 04:47 UTC
Labels: question, wrong config.json

**Comment by franzose79** [comment] 2020-11-30 10:01
Thanks, works with an updated config.
