### ISSUE TITLE
Call notification doesn't work anymore

### ISSUE THREAD

**Issue by abbanatic** [SeydX/homebridge-fritz-platform#114] opened 2020-11-12 07:44 UTC
**Describe the bug**
Call notification doesn't work anymore (Homekit and Telegram)

**To Reproduce**
1. Call my home number from my mobile

**Expected behavior**
1. a Homekit notification of an incoming call 
2. a Telegram notification of an incoming call

**Additional context**
Here's my config:

        {
            "name": "FritzPlatform",
            "debug": false,
            "devices": [
                {
                    "name": "FritzBox xxx",
                    "host": "192.168.178.1",
                    "port": 49000,
                    "username": "xxx",
                    "password": "xxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "manufacturer": "AVM",
                    "model": "7590",
                    "serialNumber": "xxx",
                    "master": true,
                    "readOnly": false,
                    "hide": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "characteristic",
                        "wps": "characteristic",
                        "dect": "characteristic",
                        "aw": "characteristic",
                        "deflection": "characteristic",
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                },
                {
                    "name": "Repeater xxx",
                    "host": "192.168.178.xxx",
                    "port": 49000,
                    "username": "xxx",
                    "password": "xxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "AVM",
                    "model": "1750E",
                    "serialNumber": "xxx",
                    "master": false,
                    "connection": "repeater",
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "characteristic",
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                },
                {
                    "name": "Repeater xxx",
                    "host": "192.168.178.xxx",
                    "port": 49000,
                    "username": "xxx",
                    "password": "xxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "AVM",
                    "model": "1750E",
                    "serialNumber": "xxxx",
                    "master": false,
                    "connection": "repeater",
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "characteristic",
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                },
                {
                    "name": "Repeater xxx",
                    "host": "192.168.178.xx",
                    "port": 49000,
                    "username": "xxx",
                    "password": "xxx",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "AVM",
                    "model": "1750E",
                    "serialNumber": "xxx",
                    "master": false,
                    "connection": "repeater",
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_5ghz": "characteristic",
                        "wifi_guest": "characteristic",
                        "led": "characteristic",
                        "lock": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "ping": false
                }
            ],
            "smarthome": [
                {
                    "name": "xxx",
                    "ain": "xxx",
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "name": "xxx",
                    "ain": "xxx",
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "name": "xxx",
                    "ain": "xxx",
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "name": "xxx",
                    "ain": "xxx",
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "name": "xxx",
                    "ain": "xxx",
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "name": "xxx",
                    "ain": "xxx",
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "name": "xxx",
                    "ain": "xxx",
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "name": "xxx",
                    "ain": "xxx",
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                }
            ],
            "callmonitor": {
                "active": true,
                "ip": "192.168.178.1",
                "port": 1012,
                "incomingTo": [
                    "750xxx",
                    "759xxx",
                    "759xxx",
                    "420xxx"
                ],
                "outgoingFrom": [
                    "750xxx"
                ]
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": true,
                    "accType": "characteristic"
                }
            },
            "options": {
                "polling": {
                    "timer": 45
                }
            },
            "telegram": {
                "active": true,
                "token": "xxx",
                "chatID": "59xxxxxxxx",
                "messages": {
                    "callmonitor": {
                        "incoming": "Anruf von @",
                        "outgoing": "Anruf zu @"
                    }
                }
            },
            "platform": "FritzPlatform"
        }

I didn't change anything on the FritzBox etc.. I even tried to install some 5.0.x versions of the plugin, but didn't succeed. It worked on Tuesday, when the new version was released.

Here's an excerpt of the debug log:

Nov 12 08:27:15 abbapie01 homebridge[12821]: [11/12/2020, 8:27:15 AM] [FritzPlatform] Callmonitor Incoming: "incomingTo" nr matched!
Nov 12 08:27:15 abbapie01 homebridge[12821]: (node:12821) UnhandledPromiseRejectionWarning: TypeError: entry.number.find is not a function
Nov 12 08:27:15 abbapie01 homebridge[12821]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/callmonitor/callmonitor.js:157:47)
Nov 12 08:27:15 abbapie01 homebridge[12821]: (Use `node --trace-warnings ...` to show where the warning was created)
Nov 12 08:27:15 abbapie01 homebridge[12821]: (node:12821) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Nov 12 08:27:15 abbapie01 homebridge[12821]: (node:12821) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Nov 12 08:27:22 abbapie01 homebridge[12821]: [11/12/2020, 8:27:22 AM] [FritzPlatform] Callmonitor Incoming: Call disconnected with 0151xxxxxxx

n -> 14.15.0
npm -> 6.14.8

Thanks and best regards,
Thomas

**Comment by SeydX** [comment] 2020-11-12 07:48
@abbanatic 

Please switch "Phonebook" on in Apple Home/Eve to generate a new phonebook.json - After that it should work again

**Comment by abbanatic** [comment] 2020-11-12 08:20
Hi,

well, that did the trick, good too know.

But in the Eve app, the phonebook always switches back to off, as soon as I tap on "ON". I observe the same behavior regarding the phonebook and other characteristics mentioned in #105.

**Comment by SeydX** [comment] 2020-11-12 13:23
@abbanatic 

Phonebook has only a ON function. Phonebook just stores the contacts to a json file and goes back to off if finished. So thats not a bug.

Ob which characteristics u have also problems?

**Comment by abbanatic** [comment] 2020-11-12 13:34
Hi,

ah, ok, thank you for the explanation.

I've found problems with the characteristic for the answering machine: I can turn it off, but I can't turn if on again.

Best regards,
Thomas

**Comment by SeydX** [comment] 2020-11-12 15:22
@abbanatic 

Version of Fritz OS ?

**Comment by abbanatic** [comment] 2020-11-12 15:33
Hm, 07.24-83411 Inhaus - that might be the problem. ()

**Comment by SeydX** [comment] 2020-11-12 15:36
@abbanatic 

I didnt try the beta firmware yet. Maybe that is the problem yes

**Comment by SeydX** [comment] 2020-11-12 18:53
Closing this issue because the main problem should be resolved. FW 7.24 will be supported in the future

**Closed by SeydX** 2020-11-12 18:53 UTC

**Comment by abbanatic** [comment] 2020-11-12 20:35
Hi,

you're right, my fault! ;) 

But if you should need debugging information to finally support firmware 7.24 on FritzBox 7590, please let me know. I'd be glad to contribute.

Besindes the answering machine, broadband and other characteristics don't work as expected.

**Comment by abbanatic** [comment] 2020-11-12 20:47
Hi,

ich habe eben einen kleinen PayPal-Beitrag für Deine tolle Arbeit geschickt.

Leider konnte ich keinen persönlichen Kommentar hinterlassen.

Daher hier:

DANKE für diese geniale Plugin und die vielen Updates und die schnelle Reaktionszeit bei Fragen und Problemen!

Viele Grüße,
Thomas
