### ISSUE TITLE
Password Fritzbox with special characters

### ISSUE THREAD

**Issue by giannimp** [SeydX/homebridge-fritz-platform#104] opened 2020-11-10 19:42 UTC
Can you add Password Fritzbox with special characters type @ # etc. ???
thank you

**Comment by BKrnk1337** [comment] 2020-11-10 20:08
Hello @giannimp the problem is already known and will be fixed by @SeydX in an upcoming update.

https://github.com/SeydX/homebridge-fritz-platform/issues/101#issuecomment-724785020

**Closed** 2020-11-10 21:03 UTC
Labels: duplicate

**Comment by SeydX** [comment] 2020-11-10 23:00
@giannimp 

fixed in v5.0.4
